[sdl]
fullscreen=false
output=surface
autolock=false

[dosbox]
machine=svga_s3
memsize=16
quit warning=false

[cpu]
core=normal
cputype=386
# DOSBox-X's CPU table puts a 386DX-40 at roughly 7,350 cycles.
cycles=fixed 7350

[mixer]
nosound=false
rate=22050

[midi]
mididevice=none

[speaker]
pcspeaker=true

[dos]
xms=true
ems=true
umb=true
