[sdl]
fullscreen=false
output=surface
autolock=false

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=normal
cputype=386
cycles=fixed 12000

[mixer]
nosound=false
rate=22050

[midi]
mididevice=none

[speaker]
pcspeaker=true

[dos]
xms=true
ems=true
umb=true
